name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
    uses: openmcp-project/build/.github/workflows/publish.lib.yaml@1dfe1496cdee935bf61006c706e5fd3ecd06b82e # main
    secrets:
      app_private_key: ${{ secrets.ODG_BOT_PRIVATE_KEY }}
    with:
      app_id: ${{ vars.ODG_BOT_APP_ID }}
