name: Renovate Generate

on:
  push:
    branches:
      - "renovate/**"

permissions:
  contents: write

jobs:
  generate:
    uses: openmcp-project/build/.github/workflows/renovate-generate.lib.yaml@ca63f82696e8311fa8494cfa59221a58f1787e59 # main
    secrets:
      app_private_key: ${{ secrets.ODG_BOT_PRIVATE_KEY }}
    with:
      app_id: ${{ vars.ODG_BOT_APP_ID }}
