name: REUSE Compliance Check

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@7ebb6321d59d975715e84d9cef0d2b802015eadc # main
