name: Validate Pull Request Content

on:
  pull_request:
    types:
      - edited
      - opened

permissions:
  contents: read

jobs:
  validate_pr_content:
    uses: openmcp-project/build/.github/workflows/validate-pr-content.lib.yaml@45b4a9ddc7707ac7a1d621e5dbec9732a0eeb84b # main
